const express = require('express')
const router = express.Router()
const { registerParent, loginParent, getMe } = require('../controllers/parent/auth')
const parentCtrl = require('../controllers/parent')
const { protectParent } = require('../middleware/parentAuth')

router.post('/parent/register', registerParent)
router.post('/parent/login', loginParent)
router.get('/parent/me', protectParent, getMe)

router.use(protectParent)
router.get('/parent/students', parentCtrl.listStudents)
router.post('/parent/students/link', parentCtrl.linkStudent)
router.delete('/parent/students/:id', parentCtrl.unlinkStudent)
router.get('/parent/cycles', parentCtrl.getCycles)
router.get('/parent/students/:id/results', parentCtrl.getResults)
router.get('/parent/students/:id/report', parentCtrl.getReport)
router.get('/parent/students/:id/performance', parentCtrl.getPerformance)
router.get('/parent/students/:id/trend', parentCtrl.getTrend)
router.get('/parent/students/:id/at-risk', parentCtrl.getAtRisk)
router.get('/parent/notifications', parentCtrl.getNotifications)
router.put('/parent/notifications/:id/read', parentCtrl.markNotificationRead)
router.put('/parent/notifications/read-all', parentCtrl.markAllNotificationsRead)
router.delete('/parent/notifications/:id', parentCtrl.deleteNotification)
router.get('/parent/messages', parentCtrl.getMessages)
router.put('/parent/messages/:id/read', parentCtrl.markMessageRead)
router.put('/parent/messages/read-all', parentCtrl.markAllMessagesRead)
router.delete('/parent/messages/:id', parentCtrl.deleteMessage)
router.post('/parent/messages', parentCtrl.sendMessage)

module.exports = router
